pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'pytest/cyy:v1'
                }
            }
            steps {
                sh 'pytest --verbose --junit-xml test-reports/results-test-calc.xml sources/test_calc.py'
                sh 'pytest --verbose --junit-xml test-reports/results-test-allure.xml sources/test_allure.py'
                sh 'pytest sources/test_allure.py --alluredir ./allure-results/'
            }
        }

    }
}
